SET SCHEMA APP;
DROP TABLE COUNTRIES;
CREATE TABLE COUNTRIES(COUNTRY VARCHAR(50));
INSERT INTO COUNTRIES(COUNTRY) VALUES ('INDIA');
INSERT INTO COUNTRIES(COUNTRY) VALUES ('PAK');
INSERT INTO COUNTRIES(COUNTRY) VALUES ('USA');
INSERT INTO COUNTRIES(COUNTRY) VALUES ('MEXICO');
SELECT * FROM COUNTRIES;

SET SCHEMA APP;
DROP TABLE CITIES;
CREATE TABLE CITIES(COUNTRY VARCHAR(50), CITY VARCHAR(50));

INSERT INTO CITIES (COUNTRY, CITY) VALUES('INDIA','TRICHY');
INSERT INTO CITIES (COUNTRY, CITY) VALUES('INDIA','CHENNAI');
INSERT INTO CITIES (COUNTRY, CITY) VALUES('INDIA','NEW DELHI');

INSERT INTO CITIES (COUNTRY, CITY) VALUES('PAK','KARACHI');
INSERT INTO CITIES (COUNTRY, CITY) VALUES('PAK','MALL');

INSERT INTO CITIES (COUNTRY, CITY) VALUES('USA','AUSTIN');
INSERT INTO CITIES (COUNTRY, CITY) VALUES('USA','NEW YORK');
INSERT INTO CITIES (COUNTRY, CITY) VALUES('USA','CHICAGO');
INSERT INTO CITIES (COUNTRY, CITY) VALUES('USA','SEATTLE');

INSERT INTO CITIES (COUNTRY, CITY) VALUES('MEXICO','BEACH');

SELECT * FROM CITIES;

SELECT * FROM COUNTRIES
JOIN CITIES
USING (COUNTRY);

UPDATE COUNTRIES 
SET COUNTRY ='CANADA' WHERE COUNTRY ='MEXICO';



SELECT * FROM COUNTRIES;
